### ISSUE TITLE
How about uWebSockets?

### ISSUE THREAD

**Issue by romeerez** [ts-stack/vs-webframework#2]
(later I notice there are discussions in the ditsmod repo, which is a better fit for this kind of feedback)

So, there is a common belief in node.js that Fastify is the fastest framework, why would they put "Fast" into their name otherwise, right?

But actually, there is a much faster framework called uWebSockets. It's a terrible name for marketing because you expect it to be a lib for websockets. And no clue regarding its speed. But actually, this is the fastest node framework that even beats Bun (see [benchmarks here](https://github.com/SaltyAom/bun-http-framework-benchmark)) and it's not supported by Bun ([explanation here](https://github.com/SaltyAom/bun-http-framework-benchmark/issues/49)).

Btw, Ditsmod is also a bad name, the good name should be simple and rememberable, like Bun, or should tell us what's so special about it - "Fast" in Fastify. 

So what I'm proposing:
1) base Ditsmod off uWebSockets
2) make people believe it gives all the same benefits as Nest, but easier. Instead of comparing perf with Fastify, better compare usability with Nest, as Nest is the target auditory. I haven't read the docs of Ditsmod yet, to be honest, but AFAIK Nest, there is a big room to make it simpler.
3) compare Ditsmod with what people believe is the fastest - Bun! If the framework overhead is minimal, it should beat Bun thanks to uWebsockets. This will give hype.

I'd really like if there was a framework similar to Nest but simpler (Dismod looks even more verbose tbh) and much faster.

**Comment by KostyaTretyak** [comment]
I saw µWebSockets at https://techempower.com/benchmarks/ (by the way, in a little more than a week, Ditsmod will also appear on this site). After getting to know µWebSockets a bit, I got the impression that the author is very bad at writing documentation for his product and has a very confused train of thought... In addition, he [got into a dispute with npmjs.com](https://unetworkingab.medium.com/beware-of-tin-foil-hattery-f738b620468c), due to the forbidden on fixing previously published versions. To me, this is extremely strange...

That's why I didn't delve further into uWebSockets, but the general impression was that uWebSockets is something fast, but not very useful for the real world.

As for "Ditsmod" being a bad name. And how do you like the name "reddit"? If you remember the word "red" maybe from the first time, then you probably wouldn't remember "dit" after a week if you hadn't heard it many times... So far I can't find a more appropriate name for my framework.

As for comparing ease of use instead of benchmarking, I've [already done that](https://dev.to/kostyatretyak/nestjs-vs-ditsmod-injection-scopes-537o). But it seems that people are not very interested in this either.

**Comment by romeerez** [comment]
That's sad, I talked on reddit about uWS and they told me the same - bad reputation. And I don't understand it, repo belongs to uNetworkingAB, top contributor is the same uNetworkingAB, is this such an evil company? Somehow we use TS and VSCode and talk on GitHub while all of these tools belong to a company that apparently did much more evil than a simple author. Two years ago there was a guy who did some things people didn't like, I can't understand why is that such a big problem and a red flag. It is a built-in web server in Bun, nobody seems to be concerned by it, but very impressed with the results. I'm not trying to convince you, just saying, because I was very surprised how people were obsessed with Bun's speed and completely ignoring uWS at the same time.

> And how do you like the name "reddit"?

The idea was to have a place where people could share links to something interesting, so I think reddit is short for "read it". Yes, it's a fine name, short and memorable.

I developed ORM for Postgres, and named it as an acronym of "Postgres ORM", but people didn't appreciate the joke, I was very frustrated by it, but then just named it after the album that I really like - Orchid. So perhaps there is something related to music, art, movie, story, culture, or anything you personally like, and that could be a great name for a lib! "How do you name the ship - so will it sail".

> As for comparing ease of use instead of benchmarking, I've [already done that](https://dev.to/kostyatretyak/nestjs-vs-ditsmod-injection-scopes-537o). But it seems that people are not very interested in this either.

Maybe dev.to isn't the best place. But also, let me criticize your article (with good intentions): it's not impressive.
DI is a great way to solve some specific problems. I think `currentUser` is a great use-case for DI. How to set current user in some common place like a middleware, and later be able to use it in any place of the system (in the service)? How to configure the logger so that when you log something it will attach the current user ID so you can filter logs by the user later? It's not straightforward in other frameworks, and if Ditsmod could support this elegantly - I guarantee that people will draw attention.

**Comment by KostyaTretyak** [comment]
> Maybe dev.to isn't the best place. But also, let me criticize your article (with good intentions): it's not impressive.

I've been published on several sources, and I'm inclined to think that people will become interested in Ditsmod when they hear more about it. By the way, unusual names can be remembered precisely because of their unusualness - this is a feature of the human psyche.

If we get into the technical details, NestJS is better only because of the number of modules written and the fact that almost any module for ExpressJS can also work on NestJS. But I have noticed that people rarely analyze these technical details. They prefer slogans like "NestJS is a framework for building efficient, scalable Node.js web applications". And the fact that these words have little to do with reality, not everyone can estimate.

**Comment by romeerez** [comment]
There is also [ExpressoTS](https://github.com/expressots/expressots) - also Nest alternative with a focus on DI. 1.4k stars, which is very good for a Nest competitor. They put the main focus on easiness to use while being compatible with Express, I guess this is the key.

I hate some slogans too, especially nonsensical ones like "blazingly fast", "next generation", but it somehow works.

You can build an efficient and scalable app by using any tool at all if done properly, let's say with Perl. In theory, it's possible. So it's not a lie, no matter how good or bad the tool is, it can have a slogan "efficient and scalable" because anything at all can be scaled, GitHub is or was written in Ruby - the slowest language - and it works well. Catchy slogan is very important.

**Comment by KostyaTretyak** [comment]
> There is also [ExpressoTS](https://github.com/expressots/expressots) - also Nest alternative with a focus on DI. 1.4k stars, which is very good for a Nest competitor.

But this framework is downloaded only 143 times per week. I wonder how 1.4k stars can be combined with [143 downloads from npmjs.com](https://www.npmjs.com/package/@expressots/cli)?

**Comment by romeerez** [comment]
That's super weird, I asked [about it here](https://github.com/expressots/expressots/discussions/114), and the author couldn't explain what's with the numbers.

Ditsmod is an alright name after getting a bit used to it.

Wish you the best of luck! Waiting to see how Distmod will compare to others on techempower.

If you don't mind, couple questions regarding techempower:

[Here I noticed](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/TypeScript/ditsmod/src/app/modules/service/db/postgres.service.ts#L11) a suspicious `max: 1` - why 1? By briefly googling the repo, I see that everyone handles it in their own way, some set 10, some pull the max connections value from db and use it, and some also use max: 1 (hyperexpress). Polkadot is using a pg `Client` instead of `Pool` - so it's also just 1 connection, but I guess that using pg `Client` in case of a single connection is more efficient.

Did you compare `postgres` with `pg`? I also heard that `postgres` is a bit faster but in my own measurements, it wasn't.

Polkadot seems to be the fastest node.js solution here, so I'm looking at how they implemented things, and [this simple update](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/polkadot/drivers/postgres.js#L20) looks more performant than [the one in Ditsmod](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/TypeScript/ditsmod/src/app/modules/service/db/postgres.service.ts#L29).

Handlebars probably will eat a bit of performance, compared to native template literal as in other solutions.

**Comment by KostyaTretyak** [comment]
> Here I noticed a suspicious max: 1 - why 1?

My tests showed better performance with "max: 1". Although this may be due to a small number of requests and cache usage on the part of PostgreSQL, and on a larger number the picture will change.

Also judging by my local tests, `postgres` is significantly faster than `pg`. As a result, even such a truncated framework as polkadot shows worse results on the PostgreSQL database (including update).

To be honest, I don't take seriously the frameworks that perform significantly better than Node.js in the "JavaScript" category because they all use either uWebSockets or Bun (or `just-js`, which is generally suitable for "Hello, World!" only tests). But I think that uWebSockets has no prospects for mass use due to, at the very least, terrible documentation. And Bun does not have a stable version yet. By the way, a couple of years ago I tested Bun and at that time it added 10-15% speed compared to Node.js, but these are not impressive results, so if Bun does become popular, it won't be soon.
